{
 "title": "Bitcoin Stats",
 "time": { "from": "2023-01-01T00:00:00.000Z", "to": "2024-12-31T00:00:00.000Z" },
 "refresh": "5s",
 "panels": [
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transactions volume | Daily",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT time, transactions\nFROM l1_btc_transactions_volume_daily \nWHERE\n  time BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Transactions Volume Standard Deviation | Hourly",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "WITH hourly_transactions AS (\n    SELECT \n        time_bucket('1 hour', timestamp) AS hour,\n        SUM(ntx) AS total_transactions\n    FROM \n        l0_btc_blocks \n    WHERE \n        timestamp BETWEEN $__timeFrom() AND $__timeTo()\n    GROUP BY \n        hour\n),\nstats AS (\n    SELECT \n        AVG(total_transactions) AS mean_transactions,\n        STDDEV(total_transactions) AS stddev_for_all_transactions\n    FROM \n        hourly_transactions\n),\nz_scores AS (\n    SELECT \n        ht.total_transactions,\n        s.mean_transactions,\n        s.stddev_for_all_transactions\n    FROM \n        hourly_transactions ht\n    CROSS JOIN \n        stats s\n),\nstddev_ranges AS (\n    SELECT \n        total_transactions,\n        CASE \n            WHEN total_transactions < (mean_transactions - 3 * stddev_for_all_transactions)\n                THEN '< 4σ'\n            WHEN total_transactions BETWEEN GREATEST(0, mean_transactions - 3 * stddev_for_all_transactions) AND (mean_transactions - 2 * stddev_for_all_transactions)\n                THEN '-3σ [0.00 - ' || ROUND(mean_transactions - 2 * stddev_for_all_transactions, 2) || ']'\n            WHEN total_transactions BETWEEN GREATEST(0, mean_transactions - 2 * stddev_for_all_transactions) AND (mean_transactions - stddev_for_all_transactions)\n                THEN '-2σ [' || ROUND(GREATEST(0, mean_transactions - 2 * stddev_for_all_transactions), 2) || ' - ' || ROUND(mean_transactions - stddev_for_all_transactions, 2) || ']'\n            WHEN total_transactions BETWEEN GREATEST(0, mean_transactions - stddev_for_all_transactions) AND mean_transactions\n                THEN '-1σ [' || ROUND(GREATEST(0, mean_transactions - stddev_for_all_transactions), 2) || ' - ' || ROUND(mean_transactions, 2) || ']'\n            WHEN total_transactions BETWEEN mean_transactions AND (mean_transactions + stddev_for_all_transactions)\n                THEN '+1σ [' || ROUND(mean_transactions, 2) || ' - ' || ROUND(mean_transactions + stddev_for_all_transactions, 2) || ']'\n            WHEN total_transactions BETWEEN (mean_transactions + stddev_for_all_transactions) AND (mean_transactions + 2 * stddev_for_all_transactions)\n                THEN '+2σ [' || ROUND(mean_transactions + stddev_for_all_transactions, 2) || ' - ' || ROUND(mean_transactions + 2 * stddev_for_all_transactions, 2) || ']'\n            WHEN total_transactions BETWEEN (mean_transactions + 2 * stddev_for_all_transactions) AND (mean_transactions + 3 * stddev_for_all_transactions)\n                THEN '+3σ [' || ROUND(mean_transactions + 2 * stddev_for_all_transactions, 2) || ' - ' || ROUND(mean_transactions + 3 * stddev_for_all_transactions, 2) || ']'\n            WHEN total_transactions > (mean_transactions + 3 * stddev_for_all_transactions)\n                THEN '> 4σ'\n        END AS stddev_range\n    FROM \n        z_scores\n)\nSELECT \n    stddev_range,\n    COUNT(*) AS hours_in_range\nFROM \n    stddev_ranges\nGROUP BY \n    stddev_range\nORDER BY \n    CASE \n        WHEN stddev_range LIKE '< 4σ%' THEN 1\n        WHEN stddev_range LIKE '-3σ%' THEN 2\n        WHEN stddev_range LIKE '-2σ%' THEN 3\n        WHEN stddev_range LIKE '-1σ%' THEN 4\n        WHEN stddev_range LIKE '+1σ%' THEN 5\n        WHEN stddev_range LIKE '+2σ%' THEN 6\n        WHEN stddev_range LIKE '+3σ%' THEN 7\n        WHEN stddev_range LIKE '> 4σ%' THEN 8\n    END;"
    }
   ]
  },
  {
   "title": "Transactions Volume Standard Deviation | Daily",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "WITH daily_totals AS (\n    SELECT \n        time_bucket('1 day', time) AS day,\n        SUM(transactions) AS total_transactions\n    FROM \n        btc_transactions_volume_daily \n    WHERE \n        time BETWEEN $__timeFrom() AND $__timeTo()\n    GROUP BY \n        day\n),\nstats AS (\n    SELECT \n        AVG(total_transactions) AS mean_transactions,\n        STDDEV(total_transactions) AS stddev_for_all_transactions\n    FROM \n        daily_totals\n),\nz_scores AS (\n    SELECT \n        dt.day,\n        dt.total_transactions,\n        s.mean_transactions,\n        s.stddev_for_all_transactions\n    FROM \n        daily_totals dt,\n        stats s\n),\nstddev_ranges AS (\n    SELECT \n        total_transactions,\n        CASE \n            WHEN total_transactions < (mean_transactions - 3 * stddev_for_all_transactions)\n                THEN '< 4σ'\n            WHEN total_transactions BETWEEN GREATEST(0, mean_transactions - 3 * stddev_for_all_transactions) AND (mean_transactions - 2 * stddev_for_all_transactions)\n                THEN '-3σ [0.00 - ' || ROUND(mean_transactions - 2 * stddev_for_all_transactions, 2) || ']'\n            WHEN total_transactions BETWEEN GREATEST(0, mean_transactions - 2 * stddev_for_all_transactions) AND (mean_transactions - stddev_for_all_transactions)\n                THEN '-2σ [' || ROUND(GREATEST(0, mean_transactions - 2 * stddev_for_all_transactions), 2) || ' - ' || ROUND(mean_transactions - stddev_for_all_transactions, 2) || ']'\n            WHEN total_transactions BETWEEN GREATEST(0, mean_transactions - stddev_for_all_transactions) AND mean_transactions\n                THEN '-1σ [' || ROUND(GREATEST(0, mean_transactions - stddev_for_all_transactions), 2) || ' - ' || ROUND(mean_transactions, 2) || ']'\n            WHEN total_transactions BETWEEN mean_transactions AND (mean_transactions + stddev_for_all_transactions)\n                THEN '+1σ [' || ROUND(mean_transactions, 2) || ' - ' || ROUND(mean_transactions + stddev_for_all_transactions, 2) || ']'\n            WHEN total_transactions BETWEEN (mean_transactions + stddev_for_all_transactions) AND (mean_transactions + 2 * stddev_for_all_transactions)\n                THEN '+2σ [' || ROUND(mean_transactions + stddev_for_all_transactions, 2) || ' - ' || ROUND(mean_transactions + 2 * stddev_for_all_transactions, 2) || ']'\n            WHEN total_transactions BETWEEN (mean_transactions + 2 * stddev_for_all_transactions) AND (mean_transactions + 3 * stddev_for_all_transactions)\n                THEN '+3σ [' || ROUND(mean_transactions + 2 * stddev_for_all_transactions, 2) || ' - ' || ROUND(mean_transactions + 3 * stddev_for_all_transactions, 2) || ']'\n            WHEN total_transactions > (mean_transactions + 3 * stddev_for_all_transactions)\n                THEN '> 4σ'\n        END AS stddev_range\n    FROM \n        z_scores\n)\nSELECT \n    stddev_range,\n    COUNT(*) AS days_in_range\nFROM \n    stddev_ranges\nGROUP BY \n    stddev_range\nORDER BY \n    CASE \n        WHEN stddev_range LIKE '< 4σ%' THEN 1\n        WHEN stddev_range LIKE '-3σ%' THEN 2\n        WHEN stddev_range LIKE '-2σ%' THEN 3\n        WHEN stddev_range LIKE '-1σ%' THEN 4\n        WHEN stddev_range LIKE '+1σ%' THEN 5\n        WHEN stddev_range LIKE '+2σ%' THEN 6\n        WHEN stddev_range LIKE '+3σ%' THEN 7\n        WHEN stddev_range LIKE '> 4σ%' THEN 8\n    END;\n"
    }
   ]
  },
  { "title": "Blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select max(height) as height\nfrom l0_btc_blocks;"
    }
   ]
  },
  {
   "title": "Block Height | Daily",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "\n\nWITH real_time_data AS (\n    SELECT time_bucket('1 day', timestamp) AS time,\n           max(height) AS height\n    FROM l0_btc_blocks\n    WHERE timestamp >= current_date\n    GROUP BY time_bucket('1 day', timestamp)\n),\nhistorical_data AS (\n    SELECT time, height\n    FROM l1_btc_block_height_daily\n    WHERE time < current_date\n)\nSELECT\n    COALESCE(h.time, r.time) AS time,\n    GREATEST(COALESCE(h.height, 0), COALESCE(r.height, 0)) AS height\nFROM historical_data h\nFULL OUTER JOIN real_time_data r\nON h.time = r.time\nORDER BY time DESC"
    }
   ]
  },
  {
   "title": "Block Difficulty",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select difficulty as difficulty\nfrom l0_btc_blocks\norder by timestamp desc\nlimit 1;"
    }
   ]
  },
  {
   "title": "Block Difficulty | Daily",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT time, difficulty\nFROM l1_btc_block_difficulty_daily\nWHERE\n  time BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY time ASC;;"
    }
   ]
  }
 ]
}